name: PR tests
on: pull_request

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"

    - name: Install Poetry and dependencies
      run: |
        python -m pip install --upgrade pip
        pip install poetry
        poetry install --no-root --all-extras

    - name: Analysing the code with black
      run: |
        poetry run black --check .

    - name: Analysing the code with ruff
      run: |
        poetry run ruff check .